version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: dnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-php

  php:
    build: ./php/php56/
    container_name: dnmp-php
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-php
      - net-mysql
      - net-redis

  mysql:
    image: mysql:latest
    container_name: dnmp-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./conf/my.cnf:/etc/mysql/my.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
      - ./log/:/var/log/dnmp/:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:latest
    container_name: dnmp-redis
    networks:
      - net-redis
    ports:
      - "6379:6379"

networks:
  net-php:
  net-mysql:
  net-redis: