nginx:
  image: nginx:latest
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./logs/nginx/:/var/log/nginx/:rw
  links:
    - php-fpm:fpm

php-fpm:
  build: ./
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/conf.d:/usr/local/etc/php/conf.d/:ro
    - ./conf/php/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    - ./logs/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql

mysql:
  image: mysql:latest
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/:/var/lib/mysql/
    - ./logs/mysql/:/var/log/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: "123456"
