version: "3"
services:
  nginx:
    image: nginx:alpine
    container_name: dnmp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
#      - ./www/:/var/www/html/:rw
      - D:/htdocs/:/var/www/html/:rw
      - ./conf/nginx/nginxconf.d:/etc/nginx/conf.d/:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx/:/var/log/dnmp/:rw
    restart: always
    networks:
      - net-php72
      - net-php56
      - net-php54
      - net-php53
  php72:
    container_name: dnmp-php72
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        XDEBUG_VERSION: 2.6.1
        SWOOLE_VERSION: 4.2.1
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
#      - ./www/:/var/www/html/:rw
      - D:/htdocs/:/var/www/html/:rw
      - ./conf/php/php72.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php72-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php/php72/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php72
      - net-mysql80
      - net-mysql5553
      - net-redis

  php56:
    container_name: dnmp-php56
    build:
      context: .
      args:
        PHP_VERSION: 5.6
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.5.5
        SWOOLE_VERSION: 2.0.11
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
#      - ./www/:/var/www/html/:rw
      - D:/htdocs/:/var/www/html/:rw
      - ./conf/php/php56.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php56-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php/php56/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php56
      - net-mysql80
      - net-mysql5553
      - net-redis

  php54:
    container_name: dnmp-php54
    build:
      context: .
      args:
        PHP_VERSION: 5.4
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.4.1
        SWOOLE_VERSION: "false"
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "false"
    expose:
      - "9000"
    volumes:
#      - ./www/:/var/www/html/:rw
      - D:/htdocs/:/var/www/html/:rw
      - ./conf/php/php54.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/php54-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/php/php54/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php54
      - net-mysql80
      - net-mysql5553
      - net-redis

  php53:
#    image: surenkid/php53:latest
    container_name: dnmp-php53
    build:
      context: .
      dockerfile: Dockerfile-php53
      args:
        PHP_VERSION: 5.3.29
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.5.5
        SWOOLE_VERSION: "false"
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "false"
    expose:
      - "9000"
    volumes:
#      - ./www/:/var/www/html/:rw
      - D:/htdocs/:/var/www/html/:rw
      - ./conf/php/php53.ini:/usr/local/etc/php/php.ini:ro
#      - ./conf/php/php53-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
#      - ./log/php/php53/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php53
      - net-mysql80
      - net-mysql5553
      - net-redis
    depends_on:
      - "mysql5553"
      - "redis"

#php 53:
#    image: surenkid/php53:latest
#    container_name: dnmp-php53
#    ports:
#      - "9000:9000"
#    networks:
#       - net-php53
#      - net-mysql80
#      - net-mysql5553
#      - net-redis
#    depends_on:
#      - "mysql5553"
#      - "redis"
#    volumes:
#     - D:/htdocs/:/var/www/html/:rw

  mysql80:
    image: mysql:8.0
    container_name: dnmp-mysql80
    ports:
      - "3380:3306"
    volumes:
      - ./conf/mysql/mysql80.cnf:/etc/mysql/conf.d/mysql.cnf:ro
#      - ./conf/mysql/mysql80/:/etc/mysql/:rw
      - ./mysql/mysql80/:/var/lib/mysql/:rw
    restart: always
    networks:
      - net-mysql80
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  mysql5553:
    image: mysql:5.5.53
    container_name: dnmp-mysql5553
    ports:
      - "5553:3306"
    volumes:
#      - ./conf/mysql/mysql5553.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./conf/mysql/mysql5553/:/etc/mysql/:rw
      - ./mysql/mysql5553/:/var/lib/mysql/:rw
      - ./tmp/:/var/tmp/:rw
    restart: always
    networks:
      - net-mysql5553
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    

  redis:
    image: redis:4.0
    container_name: dnmp-redis
    restart: always
    networks:
      - net-redis
    ports:
      - "6379:6379"


#  phpmyadmin80:
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - "8080:80"
#    networks:
#      - net-mysql80
#      - net-mysql5553
#    environment:
#      - PMA_HOST=mysql80
#      - PMA_PORT=3306

#  phpmyadmin5553:
#    image: phpmyadmin/phpmyadmin:latest
#    ports:
#      - "8080:80"
#    networks:
#      - net-mysql5553
#    environment:
#      - PMA_HOST=mysql5553
#      - PMA_PORT=3306

#  phpredisadmin:
#    image: erikdubbelboer/phpredisadmin:latest
#    ports:
#      - "8081:80"
#    networks:
#      - net-redis
#    environment:
#      - REDIS_1_HOST=redis
#      - REDIS_1_PORT=6379

networks:
  net-php72:
  net-php56:
  net-php54:
  net-php53:
  net-mysql80:
  net-mysql5553:
  net-redis:
