version: "3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/conf.d:/etc/nginx/conf.d/:ro
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/:/var/log/dnmp/:rw
    restart: always
    networks:
      - net-php72
      - net-php56
      - net-php54

  php72:
    build:
      context: .
      args:
        PHP_VERSION: 7.2
        SOURCE_LIST: stretch
        XDEBUG_VERSION: 2.6.1
        SWOOLE_VERSION: 4.2.1
        SUPPORT_MCRYPT: "false"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php72
      - net-mysql
      - net-redis

  php56:
    build:
      context: .
      args:
        PHP_VERSION: 5.6
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.5.5
        SWOOLE_VERSION: 2.0.11
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "true"
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php56
      - net-mysql
      - net-redis

  php54:
    build:
      context: .
      args:
        PHP_VERSION: 5.4
        SOURCE_LIST: jessie
        XDEBUG_VERSION: 2.4.1
        SWOOLE_VERSION: "false"
        SUPPORT_MCRYPT: "true"
        BUILT_IN_OPCACHE: "false"
    expose:
      - "9000"
    volumes:
      - ./www/:/var/www/html/:rw
      - ./conf/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./log/:/var/log/dnmp/:rw
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - net-php54
      - net-mysql
      - net-redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/:/var/lib/mysql/:rw
    restart: always
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123456"

  redis:
    image: redis:4.0
    restart: always
    networks:
      - net-redis
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - net-mysql
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "8081:80"
    networks:
      - net-redis
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379

networks:
  net-php72:
  net-php56:
  net-php54:
  net-mysql:
  net-redis: